// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niakrqggdpvtgwzwcmdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pYWtycWdnZHB2dGd3endjbWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDM4MjYsImV4cCI6MjA2NjQxOTgyNn0.IwWkNhTg_UziFbVEZHrLubVaw5ymOxGe1qYjqB6bQvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);